spring.application.name=myJournalApp

spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=journaldb
spring.data.mongodb.auto-index-creation=true
#above line is for creating the indexing from spring boot without setting up in mongodb



# if needed-
#spring.data.mongodb.username=myjournaluser
#spring.data.mongodb.password=mypassword